export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS"

export const CHANGE_HOT_RECOMMEND = "CHANGE_HOT_RECOMMEND"

export const CHANGE_NEW_ALBUM = "CHANGE_NEW_ALBUM"

export const CHANGE_UP_RAKING = "CHANGE_UP_RAKING"
export const CHANGE_NEW_RAKING = "CHANGE_NEW_RAKING"
export const CHANGE_ORIGIN_RAKING = "CHANGE_ORIGIN_RAKING"

export const CHANGE_SETTLE_SINGS = "CHANGE_SETTLE_SINGS"