export const CHANGE_CATEGORIES = "CHANGE_CATEGORIES"

export const CHANGE_CURRENT_ID = "CHANGE_CURRENT_ID"

export const CHANGE_RECOMMENDS = "CHANGE_RECOMMENDS"

export const CHANGE_RADIOS = "CHANGE_RADIOS"