export const CHANGE_CURRENT_CATEGORY = "CHANGE_CURRENT_CATEGORY"

export const CHANGE_SONG_LIST = "CHANGE_SONG_LIST"

export const CHANGE_CATEGORY = "CHANGE_CATEGORY"

export const PER_PAGE_NUMBER = 35;